import { motion, useReducedMotion } from 'framer-motion';
import NodeNetwork from '../NodeNetwork.jsx';
import { Nav, Footer, primary } from '../components/SiteChrome.jsx';

const ease = [0.22, 1, 0.36, 1];
const studio = 'https://res.cloudinary.com/drl0fxrkq/image/upload/v1774170533/Screenshot_2026-03-22_at_09.08.31_vfdgiz.png';

function useReveal() {
  const reduce = useReducedMotion();
  return { initial: reduce ? { opacity: 1 } : { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-80px' }, transition: { duration: 0.7, ease } };
}

function Hero() {
  const reduce = useReducedMotion();
  const fade = (delay) => ({ initial: reduce ? { opacity: 1 } : { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, ease, delay } });
  return <section id="home" className="relative isolate overflow-hidden pb-16 pt-36 lg:pb-20 lg:pt-44"><div aria-hidden className="pointer-events-none absolute inset-0 -z-10"><div className="absolute left-[12%] top-[-6%] h-[560px] w-[560px] rounded-full bg-signal/[0.12] blur-[150px]"></div><div className="absolute right-[6%] top-[24%] h-[460px] w-[460px] rounded-full bg-magenta/[0.10] blur-[150px]"></div><div className="grid-texture absolute inset-0"></div></div><div aria-hidden className="absolute inset-x-0 top-0 -z-10 h-[820px] opacity-40"><NodeNetwork /><div className="absolute inset-0 bg-gradient-to-b from-ink/60 via-ink/30 to-ink"></div><div className="absolute inset-x-0 bottom-0 h-1/2 bg-gradient-to-t from-ink to-transparent"></div></div><div className="mx-auto max-w-4xl px-6 text-center"><motion.p {...fade(0)} className="mb-6 inline-block rounded-full border border-white/10 bg-white/[0.03] px-4 py-1.5 font-mono text-[11px] uppercase tracking-[0.22em] text-signal/90">Shared Organisational Memory</motion.p><motion.h1 {...fade(0.08)} className="font-display text-[clamp(2.9rem,7.5vw,5.4rem)] font-bold leading-[0.98] tracking-tightest text-gradient">Your people’s judgement<br className="hidden sm:block" /> is where your brain begins.</motion.h1><motion.p {...fade(0.18)} className="mx-auto mt-7 max-w-2xl text-[18px] leading-relaxed text-white/65">Every experience, solution, relationship and story you capture becomes a living business brain. NextMonth connects the dots across your organisation’s shared memory, helping useful judgement turn into consistent operational movement.</motion.p><motion.div {...fade(0.28)} className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row"><a href="#how" style={primary} className="group relative inline-flex items-center gap-2 rounded-full px-6 py-3 text-[15px] font-semibold transition-transform hover:scale-[1.03]">How it Works <span className="transition-transform group-hover:translate-x-0.5">→</span></a></motion.div></div></section>;
}

const CARDS = [{ eyebrow: 'Stage 1 — Recognition', title: 'Every expert, one shared memory', lead: 'Experience, expertise, solving problems and knowing what works are gathered safely in one place.', points: ['Experience', 'Expertise', 'Problem Solving', 'Judgement', 'Stories'], tail: 'Your knowledge becomes organised.' }, { eyebrow: 'Stage 2 — Living Business Brain', title: 'The brain starts to understand the work', lead: 'NextMonth reads the context around every contribution, so judgement becomes searchable, reusable and connected to the real world it came from.', points: ['People', 'Projects', 'Relationships', 'Decisions', 'Opportunities'], tail: 'Your memory becomes intelligent.' }, { eyebrow: 'Stage 3 — Connection', title: 'The dots start connecting', lead: 'The living business brain works across your organisation, spotting hidden connections between experience, relationships and possible next moves.', points: ['Mentoring', 'Onboarding', 'Reusable proof', 'Better decisions', 'Consistent quality'], tail: 'Consistency no longer depends on memory.' }];
const STEPS = [{ n: '01', title: 'Start with recognition', body: 'Identify the people who carry the business in their heads and celebrate their silent contribution.' }, { n: '02', title: 'Build a Living Business Brain', body: 'NextMonth organises, indexes and interprets every piece of expertise so it becomes searchable, reusable and connected.' }, { n: '03', title: 'Connect the dots', body: 'The system continuously looks across judgement, people, projects and conversations to identify hidden opportunities.' }, { n: '04', title: 'Grow into an Organisational Brain', body: 'As the brain learns, NextMonth helps relationships, onboarding, and project work move together with consistent excellence.' }, { n: '05', title: 'Capitalise on what is already there', body: 'Turn remembered value into real work: faster onboarding, better training, and decisions that compound over time.' }];


function TransformationSection() { const reveal = useReveal(); const before = ['Great ideas disappear into conversations.', 'Useful judgement gets forgotten.', 'Onboarding takes months.', 'Relationships cool over time.', 'Opportunities stay trapped in inboxes, chats and scattered files.']; const after = ['Everything becomes connected.', 'Every project strengthens future work.', 'New starters learn from your best people.', 'Judgement becomes reusable.', 'Opportunity stays alive until it becomes action.']; return <section className="relative py-24 lg:py-32"><div aria-hidden className="pointer-events-none absolute inset-0 -z-10"><div className="absolute right-[8%] top-1/4 h-[420px] w-[420px] rounded-full bg-magenta/[0.07] blur-[140px]"></div></div><div className="mx-auto max-w-7xl px-6 lg:px-10"><motion.div {...reveal} className="mx-auto mb-14 max-w-3xl text-center"><p className="mb-4 font-mono text-[11px] uppercase tracking-[0.22em] text-white/40">The transformation</p><h2 className="font-display text-[clamp(1.9rem,4vw,3rem)] font-semibold leading-tight tracking-tightest text-gradient">Consistency stops depending on memory.</h2><p className="mx-auto mt-5 max-w-2xl text-[16.5px] leading-relaxed text-white/60">NextMonth is built around a simple promise: nothing valuable gets forgotten. Every relationship, conversation, project and piece of judgement keeps working for you.</p></motion.div><div className="grid gap-5 lg:grid-cols-2"><motion.article {...reveal} className="glass rounded-3xl p-7"><p className="mb-5 font-mono text-[11px] uppercase tracking-[0.2em] text-white/35">Before NextMonth</p><ul className="space-y-3">{before.map((item) => <li key={item} className="flex gap-3 text-[15px] leading-relaxed text-white/58"><span className="mt-[11px] h-px w-5 flex-none bg-white/20"></span>{item}</li>)}</ul></motion.article><motion.article {...reveal} className="glass rounded-3xl p-7 shadow-[0_30px_90px_-50px_rgba(43,200,244,0.7)]"><p className="mb-5 font-mono text-[11px] uppercase tracking-[0.2em] text-signal/80">With NextMonth</p><ul className="space-y-3">{after.map((item) => <li key={item} className="flex gap-3 text-[15px] leading-relaxed text-white/78"><span className="mt-[9px] h-1.5 w-1.5 rounded-full bg-signal"></span>{item}</li>)}</ul></motion.article></div></div></section>; }
function ExampleSection() { const reveal = useReveal(); const outputs = ['an interactive training guide', 'a smart onboarding plan', 'a recruitment story', 'proof for a sales meeting', 'a consistent decision-making framework']; return <section className="relative py-24 lg:py-32"><div className="mx-auto max-w-5xl px-6 lg:px-10"><motion.div {...reveal} className="glass overflow-hidden rounded-[2rem] p-8 sm:p-12"><p className="mb-5 font-mono text-[11px] uppercase tracking-[0.22em] text-white/40">A simple example</p><h2 className="font-display text-[clamp(1.8rem,3.8vw,2.8rem)] font-semibold leading-tight tracking-tightest text-gradient">One expert solution keeps creating value.</h2><p className="mt-5 max-w-2xl text-[16.5px] leading-relaxed text-white/62">An expert’s solution to a complex problem from six months ago does not sit forgotten in a folder. Connected to the right people, projects and relationships, it can become:</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{outputs.map((item) => <div key={item} className="rounded-2xl border border-white/[0.07] bg-white/[0.035] px-5 py-4 text-[15px] text-white/78">{item}</div>)}</div><p className="mt-8 border-t border-white/[0.07] pt-5 text-[16px] font-medium text-white/70">Nothing sits forgotten. Everything has the opportunity to create value again.</p></motion.div></div></section>; }

function ProductReveal() { return <section aria-label="NextMonth Studio" className="relative -mt-8 pb-8 lg:pb-12"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-64 bg-gradient-to-b from-magenta/[0.07] via-signal/[0.05] to-transparent blur-2xl"></div><motion.div initial={{ opacity: 0, y: 40 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-100px' }} transition={{ duration: 0.8, ease }} className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-10"><div className="relative overflow-hidden rounded-xl border border-white/10 bg-white/[0.02] shadow-[0_40px_120px_-20px_rgba(43,200,244,0.18)] sm:rounded-2xl"><div aria-hidden className="pointer-events-none absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-signal/60 to-transparent"></div><img src={studio} alt="The NextMonth Studio interface, showing your shared organisational memory" loading="lazy" className="block w-full" /></div></motion.div></section>; }
function WhySection() { const reveal = useReveal(); return <section className="relative py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-10"><motion.div {...reveal} className="mb-14 max-w-2xl"><p className="mb-4 font-mono text-[11px] uppercase tracking-[0.22em] text-white/40">Why NextMonth</p><h2 className="font-display text-[clamp(1.9rem,4vw,2.9rem)] font-semibold leading-tight tracking-tightest text-gradient">Judgement first. Consistency next.</h2></motion.div><div className="grid gap-5 md:grid-cols-3">{CARDS.map((c, i) => <motion.article key={c.eyebrow} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: '-60px' }} transition={{ duration: 0.6, ease, delay: i * 0.1 }} className="glass glass-hover flex flex-col rounded-3xl p-7"><p className="mb-5 font-mono text-[11px] uppercase tracking-[0.2em] text-signal/80">{c.eyebrow}</p><h3 className="font-display text-[21px] font-semibold leading-snug tracking-tight text-white">{c.title}</h3><p className="mt-3 text-[15px] leading-relaxed text-white/55">{c.lead}</p><ul className="mt-6 space-y-2.5">{c.points.map((p) => <li key={p} className="flex items-start gap-3 text-[14.5px] text-white/75"><span className="mt-[7px] h-1 w-1 flex-none rounded-full bg-signal"></span>{p}</li>)}</ul><p className="mt-6 border-t border-white/[0.07] pt-4 text-[14px] font-medium text-white/45">{c.tail}</p></motion.article>)}</div></div></section>; }
function HowSection() { const reveal = useReveal(); return <section id="how" className="relative py-24 lg:py-32"><div aria-hidden className="pointer-events-none absolute inset-0 -z-10"><div className="absolute left-[10%] top-1/3 h-[360px] w-[360px] rounded-full bg-signal/[0.07] blur-[130px]"></div></div><div className="mx-auto max-w-5xl px-6 lg:px-10"><motion.div {...reveal} className="mb-16 max-w-2xl"><p className="mb-4 font-mono text-[11px] uppercase tracking-[0.22em] text-white/40">The journey</p><h2 className="font-display text-[clamp(1.9rem,4vw,2.9rem)] font-semibold leading-tight tracking-tightest text-gradient">How it works</h2></motion.div><ol className="relative"><div aria-hidden className="absolute bottom-4 left-[27px] top-4 w-px bg-gradient-to-b from-signal/50 via-white/10 to-transparent md:left-[31px]"></div>{STEPS.map((s, i) => <motion.li key={s.n} initial={{ opacity: 0, x: -16 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, margin: '-60px' }} transition={{ duration: 0.6, ease, delay: i * 0.08 }} className="relative mb-10 flex gap-6 pl-0 last:mb-0"><div className="glass relative z-10 flex h-14 w-14 flex-none items-center justify-center rounded-2xl"><span className="font-mono text-[13px] font-semibold text-signal">{s.n}</span></div><div className="pt-1.5"><h3 className="font-display text-[22px] font-semibold tracking-tight text-white">{s.title}</h3><p className="mt-2 max-w-xl text-[15.5px] leading-relaxed text-white/60">{s.body}</p></div></motion.li>)}</ol></div></section>; }
function LivingBrainDetail() { const reveal = useReveal(); return <section id="living-brain" className="relative py-24 lg:py-32"><div className="mx-auto max-w-7xl px-6 lg:px-10"><div className="glass overflow-hidden rounded-[2rem] p-8 sm:p-12 lg:p-16"><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_0.9fr]"><motion.div {...reveal}><p className="mb-5 font-mono text-[11px] uppercase tracking-[0.22em] text-signal/80">A Living Organisational Memory</p><h2 className="font-display text-[clamp(2rem,4.4vw,3.2rem)] font-semibold leading-[1.05] tracking-tightest text-gradient">Built from the judgement of your people.</h2><p className="mt-6 max-w-xl text-[16.5px] leading-relaxed text-white/65">The living business brain is not another documentation tool. It is a dynamic environment that grows every time an expert solves a problem or makes a decision. It connects the fragmented intelligence across your organisation into one shared memory.</p><p className="mt-4 max-w-xl text-[16.5px] leading-relaxed text-white/65">Once this intelligence is visible, it helps your whole team work with the same excellence as your best people: preparing training, supporting decisions, recommending improvements, and strengthening the institutional memory behind your best work.</p></motion.div><motion.div initial={{ opacity: 0, scale: 0.96 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true, margin: '-60px' }} transition={{ duration: 0.7, ease }} className="relative"><div className="relative mx-auto aspect-square w-full max-w-sm"><div aria-hidden className="absolute inset-0 rounded-full bg-signal/[0.10] blur-3xl"></div><div className="glass relative h-full w-full rounded-3xl p-8 flex items-center justify-center text-center"><div className="space-y-4"><div className="h-16 w-16 rounded-full bg-signal/20 flex items-center justify-center mx-auto mb-6"><div className="h-3 w-3 rounded-full bg-signal animate-pulse"></div></div><p className="font-display text-xl font-bold text-white">Living Business Brain</p><p className="font-mono text-xs uppercase tracking-widest text-white/40">Continuously Learning</p></div></div></div></motion.div></div></div></div></section>; }
function FoundingSection() { const reveal = useReveal(); const perks = ['Direct access to the team', 'Early access to new capabilities', 'Influence the roadmap as NextMonth evolves']; return <section id="founding" className="relative py-24 lg:py-32"><div aria-hidden className="pointer-events-none absolute inset-0 -z-10"><div className="absolute left-1/2 top-1/2 h-[500px] w-[700px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-violet/[0.08] blur-[150px]"></div></div><div className="mx-auto max-w-3xl px-6 text-center"><motion.div {...reveal}><p className="mb-5 font-mono text-[11px] uppercase tracking-[0.22em] text-white/40">Founding customers</p><h2 className="font-display text-[clamp(2rem,4.4vw,3.2rem)] font-semibold leading-[1.06] tracking-tightest text-gradient">Building with our founding customers.</h2><p className="mx-auto mt-6 max-w-xl text-[16.5px] leading-relaxed text-white/65">We're onboarding a small number of organisations who want to help shape the future of organisational intelligence as it evolves into a living business brain for relationship-led businesses.</p></motion.div><motion.ul {...reveal} className="mx-auto mt-10 flex max-w-2xl flex-col gap-3 sm:flex-row sm:justify-center">{perks.map((p) => <li key={p} className="glass rounded-2xl px-5 py-4 text-[14px] leading-snug text-white/75 sm:flex-1">{p}</li>)}</motion.ul><motion.div {...reveal} className="mt-10"><a href="#founding" style={primary} className="inline-flex items-center gap-2 rounded-full px-7 py-3.5 text-[15px] font-semibold transition-transform hover:scale-[1.03]">Request founding access <span>→</span></a></motion.div></div></section>; }

export { FoundingSection };

export default function PlatformPage() {
  return (
    <div className="relative min-h-screen bg-ink">
      <Nav />
      <main>
        <Hero />
        <ProductReveal />
        <WhySection />
        <TransformationSection />
        <HowSection />
        <ExampleSection />
        <LivingBrainDetail />
        <FoundingSection />
      </main>
      <Footer />
    </div>
  );
}
