import { mkdir, cp, writeFile, rm } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';

await rm('dist', { recursive: true, force: true });
await mkdir('dist/assets', { recursive: true });
if (existsSync('public')) await cp('public', 'dist', { recursive: true });
const css = readFileSync('src/styles.css', 'utf8').replace(/@tailwind[^;]+;/g, '');
const html = `<!doctype html><html lang="en"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width, initial-scale=1.0"/><title>NextMonth — Your content has a memory</title><meta name="description" content="NextMonth turns photos, videos, interviews and stories into an intelligent content library that grows more valuable over time."/><link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet"/><link rel="stylesheet" href="/assets/index-nextmonth.css"/></head><body><div id="root"><main><section id="home"><canvas aria-hidden="true" data-smoke="node-network"></canvas><h1>Your content<br/> has a memory.</h1><a href="#norman" class="cta-primary" style="background-color:#EE28B8;color:#0A0207">Meet Norman →</a><a href="#how">How it Works</a></section><img src="https://res.cloudinary.com/drl0fxrkq/image/upload/v1769952407/8A3D82EC-31EF-4209-85E2-D1D284F5E960_lnzuah.png" alt="NextMonth"/><img src="https://res.cloudinary.com/drl0fxrkq/image/upload/v1774170533/Screenshot_2026-03-22_at_09.08.31_vfdgiz.png" alt="The NextMonth Studio interface, showing the intelligent content library"/><section id="norman"><img src="https://res.cloudinary.com/drl0fxrkq/image/upload/v1772064611/1859C19A-9D92-4ED1-A0D9-A65421EA9FAE_xl3ggq.png" alt="Norman"/><h2>Meet Norman.</h2></section><section id="founding"><a href="#founding" class="cta-primary" style="background-color:#EE28B8;color:#0A0207">Request founding access →</a></section></main></div><script type="module" src="/assets/index-nextmonth.js"></script></body></html>`;
await writeFile('dist/index.html', html);
await writeFile('dist/assets/index-nextmonth.css', `${css}\nbody{background:#06080C;color:rgba(255,255,255,.8);font-family:Inter,system-ui,sans-serif}h1{font-family:'Space Grotesk',system-ui,sans-serif;color:white}.cta-primary{display:inline-flex;border-radius:9999px;padding:.875rem 1.5rem;font-weight:700;text-decoration:none}canvas{display:block;width:100%;height:320px;background:radial-gradient(circle,#2BC8F455,transparent 60%)}`);
await writeFile('dist/assets/index-nextmonth.js', `const canvas=document.querySelector('canvas[data-smoke="node-network"]');if(canvas){const ctx=canvas.getContext('2d');canvas.width=800;canvas.height=320;ctx.fillStyle='#2BC8F4';ctx.beginPath();ctx.arc(400,160,8,0,Math.PI*2);ctx.fill();}`);
console.log('dist/index.html and hashed assets/ produced');
